ClientID: 201
ClientName: FireDetectionInference
ConfigFile: configFireDetectionInferenceService.yaml
CatalogURL: http://json_catalog_provider_service:8080/
CatalogUpdateIntervalCycles: 12
# REST Server config (local fallback)
RESTServerHost: localhost
RESTServerPort: 8082
RESTServerConfig: /
# Extra information 
TimeSeriesURL: http://localhost:8081/config
NormSize: 100
NormTimeUpdate: 5