ClientID: 2
ClientName: FireDetectionInference
ConfigFile: configFireDetectionInferenceService.yaml
CatalogURL: http://localhost:8081/config
CatalogUpdateIntervalCycles: 12s
# REST Server config (local fallback)
RESTServerHost: localhost
RESTServerPort: 8082
RESTServerConfig: /
# Extra information 
TimeSeriesURL: http://localhost:8081/config
NormSize: 100
NormTimeUpdate: 5