# Identification & Lifecycle
serviceID: "2002"
serviceName: "FireDetectionInference"
ConfigFile: "configFireDetectionInferenceService.yaml"
lifeTimeInterval: 20
catalogUpdateIntervalCycles: 20

# Service Discovery
CatalogURL: "http://json_catalog_provider_service:8084"
availableServices:
  - "REST"

# Communication Protocols
MQTT:
  broker: ""
  port: 1883
  topicSub:
    - ""
  topicPub:
    - ""

REST:
  serverHost: "0.0.0.0"
  serverPort: 8085
  serverConfig: "/"

# Application Specific Parameters
Extra:
  TimeSeriesURL: "http://thingspeak_service:8083"
  NormSize: 100
  NormTimeUpdate: 120