# Identification & Lifecycle
ClientID: "2002"
ClientName: "FireDetectionInference"
ConfigFile: "configFireDetectionInferenceService.yaml"
LifeTimeInterval: 20
CatalogUpdateIntervalCycles: 20

# Service Discovery
CatalogURL: "http://json_catalog_provider_service:8084"
AvailableServices:
  - "REST"

# Communication Protocols
MQTT:
  broker: ""
  port: 1883
  topicSub:
    - ""
  topicPub:
    - ""

REST:
  RESTServerHost: "0.0.0.0"
  RESTServerPort: 8085
  RESTServerConfig: "/"

# Application Specific Parameters
Extra:
  TimeSeriesURL: "http://thingspeak_service:8083"
  NormSize: 100
  NormTimeUpdate: 120