ClientID: 1
DeviceName: FireDetector
ConfigFile: configFireDetectorDevice.yaml
CatalogURL: http://localhost:8081/config
CatalogUpdateIntervalCycles : 20
LifeTimeInterval : 5
# Extra
SoundLoopDelay : 0.1
AlarmSoundFilePath : ./MicroServices/FireDetectorAlarmDevice/alarm_dev_cut.mp3
#Threshold :
#  SmokeLevel: 1.2
#  Temperature: 100