# Identification & Lifecycle
ClientID: "1001"
ClientName: "FireDetector001"
ConfigFile: "configFireDetectorDevice.yaml"
LifeTimeInterval: 20
CatalogUpdateIntervalCycles: 20

# Service Discovery
CatalogURL: "http://json_catalog_provider_service:8084"
AvailableServices:
  - ""

# Communication Protocols
MQTT:
  broker: ""
  port: 1883
  topicSub:
    - ""
  topicPub:
    - ""

REST:
  RESTServerHost: ""
  RESTServerPort: 80
  RESTServerConfig: ""

# Application Specific Parameters
Extra:
  SoundLoopDelay: 0.1
  AlarmSoundFilePath: "./MicroServices/FireDetectorAlarmDevice/alarm_dev_cut.mp3"