ClientID: 1
ClientName: FireDetector
ConfigFile: configFireDetectorDevice.yaml
CatalogURL: http://localhost:8081/config
CatalogUpdateIntervalCycles : 20
LifeTimeInterval : 5
# Extra Device Specific Configurations
BuildingID: Building_123
BuildingFloors : 5
BuildingRooms : 10
# Extra
SoundLoopDelay : 0.1
AlarmSoundFilePath : ./MicroServices/FireDetectorAlarmDevice/alarm_dev_cut.mp3