# Identification & Lifecycle
serviceID: "1"
serviceName: "JSONCatalogProviderService"
ConfigFile: "configJSONCatalogProviderService.yaml"
lifeTimeInterval: 5
catalogUpdateIntervalCycles: 20

# Service Discovery
CatalogURL: "http://localhost:8084/config"
availableServices:
  - "REST"

# Communication Protocols
MQTT:
  broker: ""
  port: 1883
  topicSub:
    - ""
  topicPub:
    - ""

REST:
  serverHost: "0.0.0.0"
  serverPort: 8084
  serverConfig: "/"

# Application Specific Parameters
Extra:
  CatalogPath: "./MicroServices/JSONCatalogProviderService/Catalogs/Catalog.json"