# Identification & Lifecycle
ClientID: "1"
ClientName: "JSONCatalogProviderService"
ConfigFile: "configJSONCatalogProviderService.yaml"
LifeTimeInterval: 5
CatalogUpdateIntervalCycles: 20

# Service Discovery
CatalogURL: "http://localhost:8084/config"
AvailableServices:
  - "REST"

# Communication Protocols
MQTT:
  broker: ""
  port: 1883
  topicSub:
    - ""
  topicPub:
    - ""

REST:
  RESTServerHost: "0.0.0.0"
  RESTServerPort: 8084
  RESTServerConfig: "/"

# Application Specific Parameters
Extra:
  CatalogPath: "./MicroServices/JSONCatalogProviderService/Catalogs/Catalog.json"