# Identification & Lifecycle
ClientID: "2001"
ClientName: "ThingSpeakService"
ConfigFile: "configThingSpeakService.yaml"
LifeTimeInterval: 5
CatalogUpdateIntervalCycles: 20

# Service Discovery
CatalogURL: "http://json_catalog_provider_service:8084"
AvailableServices:
  - ""

# Communication Protocols
MQTT:
  broker: ""
  port: 1883
  topicSub:
    - ""
  topicPub:
    - ""

REST:
  RESTServerHost: "0.0.0.0"
  RESTServerPort: 8083
  RESTServerConfig: "/"

# Application Specific Parameters
Extra:
  BaseURL: "https://api.thingspeak.com"
  ChannelId: 3249207
  ChannelConfig:
    Smoke: 1
    TVOC: 2
    Temperature: 3
    CO: 4