# Identification & Lifecycle
ClientID: "2"
ClientName: "FireButtonAlarm"
ConfigFile: "configFireButtonAlarmDevice.yaml"
LifeTimeInterval: 5
CatalogUpdateIntervalCycles: 12

# Service Discovery
CatalogURL: "http://localhost:8081/config"
AvailableServices:
  - ""

# Communication Protocols
MQTT:
  broker: ""
  port: 1883
  topicSub:
    - ""
  topicPub:
    - ""

REST:
  RESTServerHost: ""
  RESTServerPort: 80
  RESTServerConfig: ""

# Application Specific Parameters
Extra: {}