# Identification & Lifecycle
serviceID: "3"
serviceName: "FireAlarmTriggerManager"
ConfigFile: "configAlarmTriggerManager.yaml"
lifeTimeInterval: 20
catalogUpdateIntervalCycles: 12

# Service Discovery
CatalogURL: "http://json_catalog_provider_service:8084"
availableServices:
  - ""

# Communication Protocols
MQTT:
  broker: ""
  port: 1883
  topicSub:
    - ""
  topicPub:
    - ""

REST:
  serverHost: "0.0.0.0"
  serverPort: 80
  serverConfig: "/"

# Application Specific Parameters
Extra:
  threshold: 0.8
  InferenceServiceURL: "http://fire_detection_inference_service:8085"