# Identification & Lifecycle
ClientID: "2003"
ClientName: "FireAlarmTriggerManager"
ConfigFile: "configAlarmTriggerManager.yaml"
LifeTimeInterval: 20
CatalogUpdateIntervalCycles: 12

# Service Discovery
CatalogURL: "http://json_catalog_provider_service:8084"
AvailableServices:
  - ""

# Communication Protocols
MQTT:
  broker: "mosquitto_broker"
  port: 1883
  topicSub:
    - "/firedetector/+/measurements"
  topicPub:
    - "/fireAlarm"

REST:
  RESTServerHost: "0.0.0.0"
  RESTServerPort: 80
  RESTServerConfig: "/"

# Application Specific Parameters
Extra:
  threshold: 0.8
  InferenceServiceURL: "http://fire_detection_inference_service:8085"